<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>OrangeHRM_TestSuite_Search_002</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>38ca5c01-130d-4342-ae6c-74f734b7e83d</testSuiteGuid>
   <testCaseLink>
      <guid>901537f1-11d4-43e1-8368-abedcce3c782</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>fb94c437-7cbb-45f5-8305-13ef5d7e68ea</id>
         <masked>false</masked>
         <name>searchItem</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Data Driven/TC_OrangeHRM_Search_004</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e51f0abf-5ab6-4184-bebf-3a1abf769f1b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/OrangeHRM_Search_TestData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e51f0abf-5ab6-4184-bebf-3a1abf769f1b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>searchItem</value>
         <variableId>fb94c437-7cbb-45f5-8305-13ef5d7e68ea</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
